### ISSUE TITLE
Cannot find module 'babel-runtime/helpers/typeof'

### ISSUE THREAD

**Issue by mqklin** [kwelch/babel-plugin-captains-log#22]
After upgrading `webpack`, `@babel/core` and `babel-loader` to the latest version I catch this error. I can provide a repro if it's necessary, but I think it's easy to reproduce

**Comment by kwelch** [comment]
I have started a branch, but I am running through a few issues with the upgrade. 
https://github.com/kwelch/babel-plugin-captains-log/tree/update-packages

1) Filename is not defaulting as it was. 
2) `"use strict";` is being injected to the top of the tests throwing off the snapshots

**Comment by mqklin** [comment]
Sorry, I'm not familiar with babel and don't know how to write plugins. I hope some day I'll learn how to do it, but now I prefer to support OS with opencollective (as much as I can afford). If you create account there, I'll tip a few bucks to you :) Because it's very useful for debugging, we use it every day (because we are debugging every day:))

**Comment by kwelch** [comment]
I have just published a beta version `1.2.0-beta.1`. Can you install that and let me know if it resolves your error. 

My tests are still failing locally, but I tested it in a local repo and it was fine, so I may just have to live with the tests as is.

**Comment by mqklin** [comment]
Now it says `ERROR in ./src/index.js Module build failed (from ./node_modules/babel-loader/lib/index.js): Error: Cannot find module 'babel-plugin-captains-log'`

**Comment by kwelch** [comment]
Is the plugin properly located in your node modules?

I thought I had it working with another repo. 

I am on vacation but I will try to put some more time into this

**Comment by kwelch** [comment]
I pushed a branch of a different repo of mine that I used to test the beta. 

https://github.com/kwelch/da-bomb/tree/captain-log-test

I ran this to install. 

`npm install babel-plugin-captains-log --tag beta -D`

**Comment by kwelch** [comment]
@mqklin Could you try the install again.

**Comment by mqklin** [comment]
Sorry for the delay. I'll do it this week

**Comment by kwelch** [comment]
No worries! I want to make sure it works and I assume if it is not working for you it could be breaking for others. Thanks for helping test!

**Comment by mqklin** [comment]
Sorry, didn't have time =/ Will try to see this week. I want to setup it from scratch, because in my project I still get this error: ` Error: Cannot find module 'babel-plugin-captains-log'` (I'm installing it with `yarn add -D `babel-plugin-captains-log@beta`)

**Comment by mqklin** [comment]
@kwelch if I run `yarn add babel-plugin-captains-log@beta`, my `node_modules/babel-plugin-captains-log` folder has no `dist` folder: 
![image](https://user-images.githubusercontent.com/9456433/55530045-bc54ea00-56bd-11e9-9ea6-030cef50b31c.png)

But if I install it with `npm`, it has. But I can't use `npm`, because we use `yarn` in our project.

**Comment by kwelch** [comment]
oh wow that is very odd. I will try to replicate. Thanks!

**Comment by kwelch** [comment]
I found the issue with that deployment and have republished under the beta tag.

**Comment by mqklin** [comment]
It works now! Thanks a lot! 
Will you publish it as a release? Or should we use `beta`?

**Comment by kwelch** [comment]
I will merge this and publish a real release.

**Comment by kwelch** [comment]
This was resolved and pushed with c467ac784a52de644db7d14b5ee52036819a029d and v1.2.0
